 -- Phase 2: ELO & Venue Adjustments
ALTER TABLE teams ADD COLUMN elo_rating INTEGER DEFAULT 1500;
ALTER TABLE teams ADD COLUMN home_elo INTEGER DEFAULT 1500;
ALTER TABLE teams ADD COLUMN away_elo INTEGER DEFAULT 1500;
ALTER TABLE teams ADD COLUMN matches_processed INTEGER DEFAULT 0;
ALTER TABLE teams ADD COLUMN last_update TEXT;
ALTER TABLE teams ADD COLUMN home_adjustment REAL DEFAULT 0.0;
ALTER TABLE teams ADD COLUMN away_adjustment REAL DEFAULT 0.0;
