import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
import re
import sys

def main():
    # Load environment variables
    gmail_address = os.environ.get("GMAIL_ADDRESS")
    gmail_password = os.environ.get("GMAIL_APP_PASSWORD")
    recipient_email = os.environ.get("RECIPIENT_EMAIL")

    if not all([gmail_address, gmail_password, recipient_email]):
        print("Error: Missing email configuration environment variables.")
        print("Please set GMAIL_ADDRESS, GMAIL_APP_PASSWORD, and RECIPIENT_EMAIL.")
        sys.exit(1)

    output_file = "output.txt"
    if not os.path.exists(output_file):
        print(f"Error: {output_file} not found. Cannot send email.")
        sys.exit(1)

    with open(output_file, "r", encoding="utf-8") as f:
        output_content = f.read()

    # Extract the relevant part of the output (after the builder starts)
    # Finding the section that looks like an Acca slip or the main output
    start_idx = output_content.find("*** ATHENA")
    if start_idx != -1:
        extracted_content = output_content[start_idx:]
    else:
        extracted_content = output_content

    # Clean up ANSI escape codes from rich terminal output
    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
    clean_content = ansi_escape.sub('', extracted_content)

    today_str = datetime.now().strftime("%Y-%m-%d")
    subject = f"ATHENA Daily Accumulator - {today_str}"

    # Determine status
    is_success = "FULLPROOF ACCA READY" in clean_content
    is_error = "Failed" in clean_content or "error" in clean_content.lower()

    if is_success:
        banner_color = "#16a34a"  # Green
        banner_text = "SUCCESS: Acca Generated"
    elif is_error:
        banner_color = "#dc2626"  # Red
        banner_text = "WARNING: Generation Failed or Errors Occurred"
    else:
        banner_color = "#ca8a04"  # Yellow
        banner_text = "NOTICE: Check Output for Details"

    # Create HTML body
    html = f"""
    <html>
      <head>
        <style>
          body {{
            font-family: Arial, sans-serif;
            background-color: #1a1a2e;
            color: #e2e8f0;
            margin: 0;
            padding: 20px;
          }}
          .container {{
            max-width: 800px;
            margin: 0 auto;
            background-color: #16213e;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
          }}
          .header {{
            background-color: #0f3460;
            padding: 20px;
            text-align: center;
            border-bottom: 3px solid {banner_color};
          }}
          .header h1 {{
            margin: 0;
            color: #ffffff;
            font-size: 24px;
            letter-spacing: 2px;
          }}
          .banner {{
            background-color: {banner_color};
            color: #ffffff;
            text-align: center;
            padding: 10px;
            font-weight: bold;
          }}
          .content {{
            padding: 20px;
          }}
          pre {{
            background-color: #0f172a;
            color: #38bdf8;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
            font-family: 'Courier New', Courier, monospace;
            font-size: 14px;
            line-height: 1.4;
          }}
          .footer {{
            background-color: #0f3460;
            text-align: center;
            padding: 15px;
            font-size: 12px;
            color: #94a3b8;
          }}
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>ATHENA ACCUMULATOR SLIP</h1>
          </div>
          <div class="banner">
            {banner_text}
          </div>
          <div class="content">
            <pre>{clean_content}</pre>
          </div>
          <div class="footer">
            Generated by ATHENA - Fullproof Strategy Engine<br>
            Date: {today_str}
          </div>
        </div>
      </body>
    </html>
    """

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = gmail_address
    msg['To'] = recipient_email

    part = MIMEText(html, 'html')
    msg.attach(part)

    try:
        print(f"Connecting to SMTP server to send email to {recipient_email}...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(gmail_address, gmail_password)
        server.sendmail(gmail_address, recipient_email, msg.as_string())
        server.quit()
        print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
